<Project Sdk="Microsoft.NET.Sdk.Web">
  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <BlazorDisableThrowNavigationException>true</BlazorDisableThrowNavigationException>
  </PropertyGroup>
  <ItemGroup>
    <ProjectReference Include="..\iRacingCoach.BackendClient\iRacingCoach.BackendClient.csproj" />
    <ProjectReference Include="..\iRacingCoach.Coordinator\iRacingCoach.Coordinator.csproj" />
    <ProjectReference Include="..\iRacingCoach.UI\iRacingCoach.UI.csproj" />
  </ItemGroup>
</Project>
